# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.PGP_PRIVATE_KEY }}") | base64 --decode > /tmp/pgp_private_key.kbx
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - uses: gradle/gradle-build-action@v2
        id: setup-gradle
        with:
          gradle-version: "7.4"
      - name: Build with Gradle
        run: gradle build -Psigning.keyId=${{ secrets.PGP_KEY_ID }} -Psigning.password=${{ secrets.PGP_PASSWORD }} -Psigning.secretKeyRingFile="/tmp/pgp_private_key.kbx"

      - name: Publish
        run: gradle publish
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_SECRET }}